rondasgp8/src/main/java/br/upf/ads/rondasgp8/model/Pessoa.java
package br.upf.ads.rondasgp8.model;

import java.io.Serializable;
import java.util.Base64;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;

@Entity
public class Pessoa implements Serializable {  // 2) implementar Serializable
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// 1) atributos encapsulados = private 
	@Id
	private Integer id;
	private String nome;
	private String loginapp;
	private String senha;
	
	@Lob
	private byte[] foto;
	
	
	// 3) Construtor sem argumentos
	public Pessoa() {
		super();
	}
	
	public Pessoa(Integer id, String nome, String loginapp, String senha) {
		super();
		this.id = id;
		this.nome = nome;
		this.loginapp = loginapp;
		this.senha = senha;
		
	}
	
	public Pessoa(Integer id) {
		super();
		this.id = id;
	}

	public Pessoa(String nome) {
		super();
		this.nome = nome;
		
	}

	// 4) Possuir métodos get e set públicos para atributos
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLoginApp() {
		return loginapp;
	}

	public void setLoginApp(String loginapp) {
		this.loginapp = loginapp;
	}
	
	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}
	
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}


	// 6) Substituições equals, hashCode e toString	
	@Override
	public String toString() {
		return "Pessoa [id=" + id + ", nome=" + nome + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pessoa other = (Pessoa) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	public byte[] getFoto() {
		return foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}
	
	public String getFotoBase64() {
		if (foto != null)
		   return new String(Base64.getEncoder().encode(foto));
		else
		   return "";
	}
	
	
}

rondasgp8/WebContent/Privada/Pessoa/PessoaForm.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="ISO-8859-1">
</head>
<body>
	<jsp:include page="../fragmentos/Cabecalho.jsp"></jsp:include>
	<form action="PessoaCon" method="post">
		<fieldset>
		    <legend>Formulário:</legend>
	
			<div class="row">
				<div class="col-md-2">
					<label>Id</label>
	        		<input class="form-control" type="number" name="id" value="${obj.id}">
				</div>
			</div>
	
			<div class="row">
				<div class="col-md-5">
			        <label>Nome</label>
			        <input class="form-control"  type="text" name="nome" value="${obj.nome}">			
				</div>
			</div>
	
		
	
	
	
	        	
	        <button class="btn btn-primary" type="submit" name="gravar">Gravar</button>	
	        <button type="submit" name="cancelar">Cancelar</button>
		
		</fieldset>
	</form>

</body>
</html>

rondasgp8/WebContent/Privada/Pessoa/PessoaFoto.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
	<html>
	<head>
<meta charset="ISO-8859-1">
</head>
<body>
	<jsp:include page="../fragmentos/Cabecalho.jsp"></jsp:include>
		<form action="PessoaCon" method="post" enctype="multipart/form-data">
			<fieldset>
				<legend>Formulário:</legend>
				 <div class="row">
				  <div class="col-md-2">
					<label>Id</label> <input class="form-control" type="number"
					readonly="readonly" name="id" value="${obj.id}">
				</div>
		</div>
			<div class="row">
				<div class="col-md-5">
					<label>Nome</label> <input class="form-control" type="text"
						name="nome" readonly="readonly" value="${obj.nome}">
				</div>
		</div>
			<div class="row">
				<div class="col-md-2">				
					<label>Foto</label> 
					
					<input type="file" name="foto"/><br>
					
					<div id="areaImagem">
						<img name="imagem" id="imagem" width="200" height="200"
							 src="uploads/Foto${obj.id}.jpg" />
					</div>

					<br>					
					<div id="areaImagemBD">
						<img name="imagemBD" id="imagemBD" width="300" height="300"
							 src="data:image/jpg;base64,${obj.fotoBase64}" />
					</div>

				</div>
			</div>


			<button class="btn btn-primary" type="submit" name="gravarFoto">Gravar</button>
			<button class="btn btn-primary" type="submit" name="cancelar">Cancelar</button>

		</fieldset>
	</form>

</body>
</html>

rondasgp8/WebContent/Privada/Pessoa/PessoaList.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
<head>
	<meta charset="ISO-8859-1">
	
	
	

	
	
	
</head>
<body>
	<jsp:include page="../fragmentos/Cabecalho.jsp"></jsp:include>
	
		<script type="text/javascript">
	    function confirmar(){
	    	$.confirm({
	    	    title: 'Confirmar',
	    	    content: 'Confirmar a exclusão?',
	    	    type: 'orange',
	    	    typeAnimated: true,
	    	    buttons: {
	    	        Sim: { 
	    	        	text: 'Sim',
	    	            btnClass: 'btn-orange',
	    	            action: function(){ 
	    	            	$("#excluir").attr("type", "submit");
	    	            	$("#excluir").click();
	    	        	}
	    	        },
	    	        Nao: { 
	    	        	text: 'Não',
	    	            btnClass: 'btn-dark',
	    	            action: function(){ 
	    	            	// programar algo se clicou não
	    	        	}
	    	        },
	    	    }
	    	});
	    	
	    	
	    }
	</script>
	
	
	<h1>LISTAGEM DE PESSOAS</h1>
	
	<form action="PessoaCon">
		<button type="submit" name="incluir"><i class="fas fa-plus-circle"></i> Incluir</button>
		
		<table border="1" class="table table-hover table-condensed">
		    <thead>
		       <tr>
		           <td>Id</td>
		           <td>Nome</td>
		           <td></td>
		           <td></td>
		       </tr>
		    </thead>
			<c:forEach items="${lista}" var="p" varStatus="cont">
			   <tr>
			      <td>${p.id}</td>
			      <td>${p.nome}</td>    
			      <td><button type="submit" name="alterarFoto" value="${p.id}">Foto</button></td>
			      <td><button type="submit" name="alterar" value="${p.id}">Alterar</button></td>
			       <td><button type="submit" name="excluir" value="${p.id}">Excluir</button></td>
			   </tr>
		    </c:forEach>
		</table>
	</form>

</body>
</html>